
[package]
name = "gabagool"
description = "a snapshotable WASM interpreter"
version = "0.1.1"
edition = "2021"
authors = ["friendlymatthew"]
license = "Apache-2.0"

[dependencies]

[target.'cfg(unix)'.dependencies]
libc = "0.2.183"

[build-dependencies]
wast = { version = "245.0.1", optional = true }
cc = { version = "1.2.57", optional = true }
object = { version = "0.38.1", optional = true }

[features]
core-tests = ["wast"]
component-tests = []
jit = ["cc", "object"]

[dev-dependencies]
insta = "1"
wat = "1"
criterion = "0.8.2"
wasmi = "1.0.9"

[[test]]
name = "core_tests"
path = "tests/core_tests.rs"
harness = false
required-features = ["core-tests"]

[[bench]]
name = "programs"
harness = false
