[package]
name = "gabagool-debug-adapter"
description = "Debug adapter protocol server for gabagool"
version.workspace = true
edition.workspace = true

[dependencies]
gabagool = { path = "../gabagool", version = "0.1.1" }
serde_json = "1"
wast = "245"

[dev-dependencies]
base64 = "0.22"
insta = "1"
